# Pandas - Exercise Solutions

## Directions

In this workbook, you'll use the Python library `pandas` to load, analyze, and manipulate flight data.

The `pandas` library is pre-installed in Colab, but don't forget to import the modules you need.

We strongly encourage you to use Google or AI to help you solve these problems. Both Google and AI are powerful tools to help you learn which functions a library provides and how to use them.

Additionally, the documentation is also available as a reference: https://pandas.pydata.org/docs/

## Intro

You are an airline operations analyst tasked with investigating and improving the efficiency of flight schedules. To do this, you manipulate flight data to identify delay patterns, perform calculations, and sort data to uncover insights, helping you make data-driven decisions to improve airline operations.

## Exercise 1 - Loading data into a DataFrame

### 🚨 New Concept: Creating a DataFrame from data

A DataFrame is a key data structure in Pandas. Its like a table in a spreadsheet or database, consisting of rows and columns, where:

- **Rows** represent individual records or data points (e.g., a person's information).
- **Columns** represent different variables or features (e.g., age, name, salary).

Each column can have a different data type (like numbers, text, or dates), and the DataFrame allows for easy data manipulation and analysis, such as filtering, grouping, and calculating statistics.

Think of it as a flexible table with labeled rows and columns that lets you perform powerful data operations quickly.

Data presented as a collection (like a list or dictionary) of a collection can be converted into a DataFrame. For example, the following list of lists can be converted into a DataFrame:

In [ ]:
import pandas as pd

data = [
    [1, 'Alice', 24, 'New York', 55000, 'HR'],
    [2, 'Bob', 27, 'San Francisco', 62000, 'Engineering'],
    [3, 'Charlie', 22, 'Los Angeles', 48000, 'Marketing'],
    [4, 'David', 32, 'Chicago', 73000, 'Finance'],
    [5, 'Eva', 29, 'Boston', 68000, 'Sales']
]

pd.DataFrame(data)

   0        1   2              3      4            5
0  1    Alice  24       New York  55000           HR
1  2      Bob  27  San Francisco  62000  Engineering
2  3  Charlie  22    Los Angeles  48000    Marketing
3  4    David  32        Chicago  73000      Finance
4  5      Eva  29         Boston  68000        Sales

### Part A

Before diving into any analysis, you need to first load the flight data into a manageable format. By loading the data into a `pandas` DataFrame, you can easily manipulate and analyze it.

Load the provided flight data into a `pandas` DataFrame and output the result.

**Solution**

In [ ]:
import pandas as pd

data = [
    {'Flight_Number': 'DL600', 'Destination': 'LAX', 'Departure_Delay': -10, 'Arrival_Delay': 5},
    {'Flight_Number': 'AA900', 'Destination': 'ORD', 'Departure_Delay': 10, 'Arrival_Delay': 15},
    {'Flight_Number': 'UA700', 'Destination': 'JFK', 'Departure_Delay': 20, 'Arrival_Delay': 25},
    {'Flight_Number': 'UA1100', 'Destination': 'ORD', 'Departure_Delay': 20, 'Arrival_Delay': 25},
    {'Flight_Number': 'UA300', 'Destination': 'LAX', 'Departure_Delay': 30, 'Arrival_Delay': 45},
    {'Flight_Number': 'AA500', 'Destination': 'ORD', 'Departure_Delay': 25, 'Arrival_Delay': 30},
    {'Flight_Number': 'DL1000', 'Destination': 'ORD', 'Departure_Delay': 15, 'Arrival_Delay': 45},
    {'Flight_Number': 'SW400', 'Destination': 'SFO', 'Departure_Delay': 0, 'Arrival_Delay': -10},
    {'Flight_Number': 'SW800', 'Destination': 'LAX', 'Departure_Delay': 35, 'Arrival_Delay': 40},
    {'Flight_Number': 'AA100', 'Destination': 'LAX', 'Departure_Delay': 15, 'Arrival_Delay': 10},
    {'Flight_Number': 'DL200', 'Destination': 'JFK', 'Departure_Delay': -5, 'Arrival_Delay': 0},
]


flight_info = pd.DataFrame(data)
flight_info

   Flight_Number Destination  Departure_Delay  Arrival_Delay
0          DL600         LAX              -10              5
1          AA900         ORD               10             15
2          UA700         JFK               20             25
3         UA1100         ORD               20             25
4          UA300         LAX               30             45
5          AA500         ORD               25             30
6         DL1000         ORD               15             45
7          SW400         SFO                0            -10
8          SW800         LAX               35             40
9          AA100         LAX               15             10
10         DL200         JFK               -5              0

To create a DataFrame without flight data, we pass our data to `DataFrame()`. When we output the DataFrame, our data is displayed in a table.

Note that when casting a list of dictionaries (like `data`) to a DataFrame, the resulting DataFrame automatically recognizes the dictionary keys as column names. When casting a list of lists to a DataFrame (as in the example given in the New Concept), this is not the case.

### Part B

Now that you have the data in a DataFrame, you want to pull up the first two flights to show a co-worker.

Display the first two rows of the DataFrame.

**Solution**

In [ ]:
flight_info.head(2)

  Flight_Number Destination  Departure_Delay  Arrival_Delay
0         DL600         LAX              -10              5
1         AA900         ORD               10             15

To display the first two rows of a DataFrame, we use the `.head()` function with the argument 2.

### Part C

To get a general sense of the delays and other numeric data, you need to generate summary statistics. This will help you quickly identify any outliers or unusual data points.

Use a single `pandas` method to generate summary statistics (count, mean, standard deviation, etc) for the DataFrame to get an overview of the data.

**Solution**

In [ ]:
flight_info.describe()

       Departure_Delay  Arrival_Delay
count        11.000000      11.000000
mean         14.090909      20.909091
std          14.286039      18.549688
min         -10.000000     -10.000000
25%           5.000000       7.500000
50%          15.000000      25.000000
75%          22.500000      35.000000
max          35.000000      45.000000

The `.describe()` method summarizes statistics about the numerical columns in a DataFrame. Here, the departure and arrival delays are the numerical columns, so the `.describe()` method provides information on those.

## Exercise 2 - Filtering a DataFrame

### 🚨 New Concept: Filtering data in a DataFrame

Filtering data in a DataFrame is essential to focus on specific subsets of data, making analysis more efficient and targeted. You might filter data to:

1. **Exclude irrelevant rows**: Remove rows that don't meet certain criteria (e.g., values below a threshold).
2. **Analyze specific conditions**: Narrow the data to analyze certain conditions (e.g., sales from a particular region).
3. **Improve performance**: Work with smaller, more manageable datasets by removing unneeded data.

**How to filter data in a DataFrame by condition**:

`df[df['column'] > value]` filters rows where a column's values are greater than a specified value.

The condition, `df['column'] > value`, checks if each value in the specified column is greater than `value` and returns a `pandas` Series. A Series is basically just a DataFrame with one column.

If the the column value is greater than `value`, the corresponding entry in the Series is `True`. If not, the entry is `False`.

For example, we can filter the below data frame to only display students born after 01-01-2001:

In [ ]:
import pandas as pd

data = {
    'Name': ['Alice Johnson', 'Bob Smith', 'Charlie Brown', 'Diana Prince', 'Evan Davis'],
    'Student_ID': ['S001', 'S002', 'S003', 'S004', 'S005'],
    'Major': ['Computer Science', 'Mathematics', 'Mathematics', 'Biology', 'Mathematics'],
    'Year_in_School': ['Sophomore', 'Junior', 'Senior', 'Freshman', 'Senior'],
    'Birthday': ['2002-05-14', '2001-08-22', '2000-12-01', '2003-03-17', '1999-07-09']
}

df = pd.DataFrame(data)

df[df["Birthday"] > "2001-01-01"]

            Name Student_ID             Major Year_in_School    Birthday
0  Alice Johnson       S001  Computer Science      Sophomore  2002-05-14
1      Bob Smith       S002       Mathematics         Junior  2001-08-22
3   Diana Prince       S004           Biology       Freshman  2003-03-17

The filter `df["Birthday"] > "2001-01-01"` tests each value in the `"Birthday"` column and creates a Series:

In [ ]:
df["Birthday"] > "2001-01-01"

0     True
1     True
2    False
3     True
4    False
Name: Birthday, dtype: bool

We then use that Series to filter the DataFrame:

In [ ]:
df[df["Birthday"] > "2001-01-01"]

            Name Student_ID             Major Year_in_School    Birthday
0  Alice Johnson       S001  Computer Science      Sophomore  2002-05-14
1      Bob Smith       S002       Mathematics         Junior  2001-08-22
3   Diana Prince       S004           Biology       Freshman  2003-03-17

### Part A

You are particularly interested in analyzing the flights to LAX because it’s one of the busiest destinations. Filtering the data will allow you to focus on the specific flights you are interested in.

Create a new DataFrame that contains only the flights to LAX.

**Solution**

To filter out LAX flights, we specify a conditional expression, `flight_info['Destination'] == 'LAX'`, to check each row's Destination column to see if is equal to "LAX". This returns a `pandas` data type called a Series, containing boolean values for each column.

In [ ]:
flight_info['Destination'] == 'LAX'

0      True
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8      True
9      True
10    False
Name: Destination, dtype: bool

We then use this Series to filter `flight_info` by wrapping it in `flight_info[]`. Only the rows in `flight_info` where the Series returned `True` will be included in the new `flights_to_lax` DataFrame.

In [ ]:
flights_to_lax = flight_info[flight_info['Destination'] == 'LAX']
flights_to_lax

  Flight_Number Destination  Departure_Delay  Arrival_Delay
0         DL600         LAX              -10              5
4         UA300         LAX               30             45
8         SW800         LAX               35             40
9         AA100         LAX               15             10

### Part B

Flights with significant delays need special attention as they impact scheduling and customer satisfaction. Filtering these flights will help you identify which ones require further analysis or intervention.

Filter and display the flights with an arrival delay greater than 20 minutes.

**Solution**

Using a similar process to Part A, we specify the conditional expression `flight_info['Arrival_Delay'] > 20` to create a Series where a row is `True` if the delay is longer than 20 minutes.

In [ ]:
flight_info['Arrival_Delay'] > 20

0     False
1     False
2      True
3      True
4      True
5      True
6      True
7     False
8      True
9     False
10    False
Name: Arrival_Delay, dtype: bool

Then, we use that to filter `flight_info` and create a new DataFrame `significant_delays` containing only flights with an arrival delay longer than 20 minutes.

In [ ]:
significant_delays = flight_info[flight_info['Arrival_Delay'] > 20]
significant_delays

  Flight_Number Destination  Departure_Delay  Arrival_Delay
2         UA700         JFK               20             25
3        UA1100         ORD               20             25
4         UA300         LAX               30             45
5         AA500         ORD               25             30
6        DL1000         ORD               15             45
8         SW800         LAX               35             40

## Exercise 3 - Calculations with DataFrames

### 🚨 New Concept: Creating new DataFrame columns

After a DataFrame is created, you can add a new column to it like this:

In [ ]:
import pandas as pd

data = {
    'Month': ['January', 'February', 'March', 'April', 'May', 'June'],
    'Region_A_Sales': [2300, 3400, 4100, 3200, 2800, 3600],
    'Region_B_Sales': [1800, 2200, 2700, 2100, 1900, 2500],
}

df = pd.DataFrame(data)

# Add new columns
df['Region_A_Tax'] = df['Region_A_Sales'] * 0.2
df['Region_B_Tax'] = df['Region_B_Sales'] * 0.2

df

      Month  Region_A_Sales  Region_B_Sales  Region_A_Tax  Region_B_Tax
0   January            2300            1800         460.0         360.0
1  February            3400            2200         680.0         440.0
2     March            4100            2700         820.0         540.0
3     April            3200            2100         640.0         420.0
4       May            2800            1900         560.0         380.0
5      June            3600            2500         720.0         500.0

### Part A

Your boss points out that calculating the total delay of each flight (by summing departure and arrival delays) would provide a more complete view of the overall flight status.

Add a new column to the DataFrame that calculates the total delay for each flight.

**Solution**

In [ ]:
flight_info['Total_Delay'] = flight_info['Departure_Delay'] + flight_info['Arrival_Delay']
flight_info

   Flight_Number Destination  Departure_Delay  Arrival_Delay  Total_Delay
0          DL600         LAX              -10              5           -5
1          AA900         ORD               10             15           25
2          UA700         JFK               20             25           45
3         UA1100         ORD               20             25           45
4          UA300         LAX               30             45           75
5          AA500         ORD               25             30           55
6         DL1000         ORD               15             45           60
7          SW400         SFO                0            -10          -10
8          SW800         LAX               35             40           75
9          AA100         LAX               15             10           25
10         DL200         JFK               -5              0           -5

We add a new column to a DataFrame similar to how we add a new dictionary entry; we simply specify the name of the column in between square brackets. Then, we calculate the total delay (arrival + departure) by adding the DataFrame columns together.

### Part B

To gauge the overall performance, you need to know the **average total delay** across all flights. This metric will give you an idea of how delays are impacting the schedule on average.

Calculate the average total delay for all flights.

**Solution**

In [ ]:
average_delay_all = flight_info['Total_Delay'].mean()
average_delay_all

35.0

The `pandas` library has statistics methods available to be used on DataFrames. Using the `.mean()` method, we can quickly find the average of all the values in the `Total_Delay` column.

### Part C

A coworker tells you that flights going to ORD are especially delayed today. To investigate this, you would like to calculate the average delay for these flights.

Calculate the average total delay for flights to ORD.

**Solution**

First, we create a new DataFrame that contains only the flights to ORD.

In [ ]:
flights_to_ord = flight_info[flight_info['Destination'] == 'ORD']
flights_to_ord

  Flight_Number Destination  Departure_Delay  Arrival_Delay  Total_Delay
1         AA900         ORD               10             15           25
3        UA1100         ORD               20             25           45
5         AA500         ORD               25             30           55
6        DL1000         ORD               15             45           60

Then, we use the `.mean()` method to calculate the average value of the `Total_Delay` column.

In [ ]:
flights_to_ord = flight_info[flight_info['Destination'] == 'ORD']
average_delay_ord = flights_to_ord['Total_Delay'].mean()
average_delay_ord

46.25

## Exercise 4 - Sorting DataFrames

### Part A

Identifying the flights with the longest total delays is crucial for prioritizing efforts to reduce delays. Sorting the data by total delay will help you pinpoint the worst offenders.

Sort the DataFrame by `Total_Delay` in descending order to identify flights with the most significant delays.

**Solution**

In [ ]:
sorted_delays = flight_info.sort_values(by='Total_Delay', ascending=False)
sorted_delays

   Flight_Number Destination  Departure_Delay  Arrival_Delay  Total_Delay
4          UA300         LAX               30             45           75
8          SW800         LAX               35             40           75
6         DL1000         ORD               15             45           60
5          AA500         ORD               25             30           55
2          UA700         JFK               20             25           45
3         UA1100         ORD               20             25           45
1          AA900         ORD               10             15           25
9          AA100         LAX               15             10           25
0          DL600         LAX              -10              5           -5
10         DL200         JFK               -5              0           -5
7          SW400         SFO                0            -10          -10

To sort the DataFrame by `Total_Delay` in descending order, we use the `.sort_values()` method. We pass in the column we wish to sort, and specify `ascending=False` to sort in descending order.

### Part B

Departure delays can have a cascading effect on the entire schedule. By sorting flights by departure delay in ascending order, you can see which flights are typically on time or early, helping you identify patterns or successful strategies.

Sort the DataFrame by `Departure_Delay` in ascending order to identify flights with minimal or no departure delays.

**Solution**

In [ ]:
sorted_delays = flight_info.sort_values(by='Departure_Delay', ascending=True)
sorted_delays

   Flight_Number Destination  Departure_Delay  Arrival_Delay  Total_Delay
0          DL600         LAX              -10              5           -5
10         DL200         JFK               -5              0           -5
7          SW400         SFO                0            -10          -10
1          AA900         ORD               10             15           25
6         DL1000         ORD               15             45           60
9          AA100         LAX               15             10           25
2          UA700         JFK               20             25           45
3         UA1100         ORD               20             25           45
5          AA500         ORD               25             30           55
4          UA300         LAX               30             45           75
8          SW800         LAX               35             40           75

Similar to Part A, we use the `.sort_values()` method. This time, to sort in ascending order, we specify the keyword argument `ascending=True`.